/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var e="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(a==Array.prototype||a==Object.prototype)return a;a[c]=b.value;return a},f=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");},h=f(this),k=function(a,c){if(c)a:{var b=h;a=a.split(".");for(var d=0;d<a.length-
1;d++){var g=a[d];if(!(g in b))break a;b=b[g]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&e(b,a,{configurable:!0,writable:!0,value:c})}};k("Object.is",function(a){return a?a:function(c,b){return c===b?0!==c||1/c===1/b:c!==c&&b!==b}});k("Array.prototype.includes",function(a){return a?a:function(c,b){var d=this;d instanceof String&&(d=String(d));var g=d.length;b=b||0;for(0>b&&(b=Math.max(b+g,0));b<g;b++){var p=d[b];if(p===c||Object.is(p,c))return!0}return!1}});
k("String.prototype.includes",function(a){return a?a:function(c,b){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(c instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(c,b||0)}});var l="ar az de en-GB en-XC en es-419 es fr it ja ko nl pl pt-BR pt ru sv th tr uk zh zh-CN zh-TW".split(" "),m=[],n=/^\?.*hl=([^&]*)/.exec(window.location.search);n&&n[1]&&m.push(n[1]);var q=window.navigator;q&&(q.languages&&(m=m.concat(q.languages)),q.language&&m.push(q.language),q.userLanguage&&m.push(q.userLanguage),q.browserLanguage&&m.push(q.browserLanguage),q.systemLanguage&&m.push(q.systemLanguage));for(var r="en",t=0;t<m.length;t++)if(0<=l.indexOf(m[t])){r=m[t];break}var u=document.createElement("script");
if("en"===r)u.src="./bundle.js";else{var v=r.toLowerCase().replace(/-/g,"_");u.src="./bundle__"+v+".js"}console.log("Using "+u.src);document.body.appendChild(u);document.body.setAttribute("lang",r);["ar","en-XB"].includes(r)&&document.body.setAttribute("dir","rtl");
